predict: false
checkpoint: ""

seed: 42
device: cpu
verbose: true

engine:
  type: torch

problem:
  name: books_rating

wandb: false
wandb_project: book-rating-prediction
run_name: ""

train:
  run_dir: saved/runs
  submit_dir: saved/submit

dataset:
  data_path: data/
  valid_ratio: 0.2

batch_size: 256
lr: 1e-3
summary_dim : 256

data:
  pipeline: books_rating_v2
  transforms:
    global: []
    post: []

recipe: bert_jhd_regression
model: BPR

model_args:
  BPR:
    embedding_size: 64
    reg_weight: 1e-4

  bert_jhd:
    embed_dim: 32
    n_heads: 4
    n_layers: 2
    dropout: 0.1
    num_features: 6
    cardinality: [1000, 500, 200, 50, 20, 10]

  CatBoost:
    iterations: 200
    depth: 8
    learning_rate: 0.05
    loss_function: RMSE
    random_seed: 42
    verbose: 100

torch:
  epochs: 1
  batch_size: 64
  lr: 1e-3
  amp: false
  grad_clip: 0.0

recbole:
  dataset: rrs
  work_dir: ${setting.run_dir}/recbole   # recbole data/ckpt/log 모아두는 폴더
  overrides: {}

recbole_train:
  seed: 42
  epochs: 50
  train_batch_size: 2048
  eval_batch_size: 4096
  learning_rate: 0.001
  device: cuda