# configs/sklearn_catboost.yaml

# --------------------
# execution
# --------------------
predict: false
checkpoint: ""
seed: 42
device: cpu
verbose: true

# --------------------
# engine
# --------------------
engine:
  type: sklearn_regression

# --------------------
# problem
# --------------------
problem:
  name: books_rating

# --------------------
# run / logging
# --------------------
wandb: true
wandb_project: book-rating-prediction
run_name: "test"
memo: | 

train:
  run_dir: saved/runs
  submit_dir: saved/submit

# --------------------
# data
# --------------------
dataset:
  data_path: data/
  valid_ratio: 0.2

data:
  pipeline: books_rating_v1   # CatBoost용 DF 기반 pipeline
  transforms:
    global: []
    post: []

# --------------------
# model
# --------------------
model: CatBoost

model_args:
  CatBoost:
    iterations: 200
    depth: 8
    learning_rate: 0.05
    loss_function: RMSE
    random_seed: 42
    verbose: 100
